browser_mod: !include ../includes/config/browser_mod.config.yaml
frontend: !include ../includes/config/frontend.config.yaml
lovelace: !include ../includes/config/lovelace.config.yaml
lovelace_gen:
  core_config: !include ../core.config.yaml
