####################################################################
#
#         TEMPLATE SENSORS
#
####################################################################
sensor: !include_dir_merge_list ../includes/sensors/
