####################################################################
#         RECORDER
####################################################################
# https://www.home-assistant.io/integrations/recorder/

##################################################################
#
#                 EXAMPLE CONFIG
#
##################################################################
#
# db_url: !secret recorder_maria_db_url
