#################################################
#
#         BASE
#
#################################################
base:
  variables:
    state: |
      [[[
        return entity && entity.state ? entity.state : null; 
      ]]]
    timeout: >
      [[[ return entity === undefined || Date.now() - Date.parse(entity.last_changed); ]]]
    light_color: !include styles/light_color.styles.yaml
  aspect_ratio: 1/1
  show_state: true
  show_icon: true
  show_label: true
  tap_action:
    animation_card: |
      [[[
        const animation_speed_ms = 900;
        const animation = `card_bounce ${animation_speed_ms}ms cubic-bezier(0.22, 1, 0.36, 1)`;
        this.shadowRoot.getElementById("card").style.animation = animation;
        window.setTimeout(() => {
          this.shadowRoot.getElementById("card").style.animation = "none";
        }, animation_speed_ms)
      ]]]
    action: toggle
    haptic: medium
  styles:
    ############################################################################
    #       LOCK
    ############################################################################
    lock:
      - justify-content: >
          [[[
            const active = 'center';
            const inactive = 'flex-end';

            const onState = ['on', 'home', 'active', 'enabled', 'heat', 'cool', 'open'];
            const offState = ['off', 'unknown', 'unavailable', 'disabled', 'closed'];

            if (!variables.state) {
              return inactive;
            }
            
            return onState.some(state => variables.state.toLowerCase().includes(state)) ? active : inactive;
          ]]]
      - align-items: >
          [[[
            const active = 'center';
            const inactive = 'flex-start';

            const onState = ['on', 'home', 'active', 'enabled', 'heat', 'cool', 'open'];
            const offState = ['off', 'unknown', 'unavailable', 'disabled', 'closed'];

            if (!variables.state) {
              return inactive;
            }
            
            return onState.some(state => variables.state.toLowerCase().includes(state)) ? active : inactive;
          ]]]
      - !include styles/card_color.styles.yaml

    ############################################################################
    #       GRID (#container)
    ############################################################################
    grid:
      - align-items: start
      - gap: 2%
      - grid-template-areas: |
          "i    s"
          "n    n"
          "l    l"
      - grid-template-columns: repeat(2, 1fr)
      - grid-template-rows: auto repeat(2, min-content)

    ############################################################################
    #       ICON (#img-cell > ha-icon)
    ############################################################################
    icon:
      - --mdc-icon-size: 35px
      - grid-area: 'i'
      - text-align: left
      - width: 100%
      - !include styles/card_color.styles.yaml

    ############################################################################
    #       NAME (#name)
    #       The name is used underneath the app icon
    ############################################################################
    name:
      - font-size: 1.2rem
      - font-weight: 600
      - grid-area: 'n'
      - justify-self: flex-start
      - letter-spacing: 0.05vw
      - line-height: 1.25rem
      - !include styles/card_color.styles.yaml

    ############################################################################
    #       LABEL (#label)
    #       Last status change
    ############################################################################
    label:
      - align-self: flex-start
      - font-size: 1rem
      - font-weight: 600
      - grid-area: 'l'
      - justify-self: flex-start
      - letter-spacing: 0.05vw
      - line-height: 1.25rem
      - !include styles/card_color.styles.yaml

    ############################################################################
    #       STATE
    ############################################################################
    state:
      - border-radius: 1rem
      - font-size: 1rem
      - font-weight: 600
      - grid-area: 's'
      - margin-top: .25rem
      - padding: 0.25rem 0.5rem
      - place-self: start end
      - !include styles/card_background-color-invert.styles.yaml
      - !include styles/card_color-invert.styles.yaml

    ############################################################################
    #       CARD (#ha-card)
    ############################################################################
    card:
      - border-radius: var(--nolu-button-card-border-radius, 1rem)
      - padding: 10%
      - !include styles/card_ripple.styles.yaml
      - !include styles/card_color.styles.yaml
      - !include styles/card_background-color.styles.yaml

  extra_styles: |
    @keyframes card_bounce {
      0% {
        transform: scale(1);
      }
      15% {
        transform: scale(0.9);
      }
      25% {
        transform: scale(1);
      }
      30% {
        transform: scale(0.98);
      }
      100% {
        transform: scale(1);
      }
    }
