#################################################
#
#         BASE
#
#################################################
base:
  variables:
    state: |
      [[[
        return entity && entity.state ? entity.state : null; 
      ]]]
    timeout: >
      [[[ return entity === undefined || Date.now() - Date.parse(entity.last_changed); ]]]
    light_color: !include styles/light_color.styles.yaml
  aspect_ratio: 1/1
  show_state: true
  show_icon: true
  show_label: true
  tap_action:
    animation_card: |
      [[[
        const animation_speed_ms = 900;
        const animation = `card_bounce ${animation_speed_ms}ms cubic-bezier(0.22, 1, 0.36, 1)`;
        this.shadowRoot.getElementById("card").style.animation = animation;
        window.setTimeout(() => {
          this.shadowRoot.getElementById("card").style.animation = "none";
        }, animation_speed_ms)
      ]]]
    action: toggle
    haptic: medium
  styles:
    ############################################################################
    #       LOCK
    ############################################################################
    lock: !include styles/lock_default.styles.yaml

    ############################################################################
    #       GRID (#container)
    ############################################################################
    grid: !include styles/grid_default.styles.yaml

    ############################################################################
    #       ICON (#img-cell > ha-icon)
    ############################################################################
    icon: !include styles/icon_default.styles.yaml

    ############################################################################
    #       NAME (#name)
    #       The name is used underneath the app icon
    ############################################################################
    name: !include styles/name_default.styles.yaml

    ############################################################################
    #       LABEL (#label)
    #       Last status change
    ############################################################################
    label: !include styles/label_default.styles.yaml

    ############################################################################
    #       STATE
    ############################################################################
    state: !include styles/state_default.styles.yaml

    ############################################################################
    #       CARD (#ha-card)
    ############################################################################
    card: !include styles/card_default.styles.yaml

  extra_styles: |
    @keyframes card_bounce {
      0% {
        transform: scale(1);
      }
      15% {
        transform: scale(0.9);
      }
      25% {
        transform: scale(1);
      }
      30% {
        transform: scale(0.98);
      }
      100% {
        transform: scale(1);
      }
    }
