####################################################################
#
#         SYSTEM_MONITOR
#
####################################################################
# https://www.home-assistant.io/integrations/systemmonitor/
- platform: systemmonitor
  resources:
    - type: processor_use
    # - type: processor_temperature -> Won't work in Virtual Machine
    - type: memory_free
    - type: disk_use_percent
      arg: /
    - type: disk_use
    - type: disk_free
    - type: throughput_network_in
      arg: enp0s3
    - type: throughput_network_out
      arg: enp0s3
