####################################################################
#
#         EXAMPLE BINARY SENSORS
#
####################################################################
# https://www.home-assistant.io/integrations/template/
binary_sensor:

  ##################################################################
  #
  #                 EXAMPLE CONFIG
  #
  ##################################################################
  #
  #
  # - platform: template
  #   sensors:
