#################################################
#
#         CUSTOM CONFIG
#
#################################################
home:
  title: 'Home'
  icon: 'mdi:home-assistant'
  url: 'home'
  show_in_navbar: true
  show_header: true
  rows:
    - widgets:
        #################################################
        #         WEATHER EXAMPLE
        #################################################
        - type: default_weather
          entity: weather.noluhass

        #################################################
        #         MARKDOWN EXAMPLE
        #################################################
        - type: markdown
          content: 'Just a markdown card'

        #################################################
        #         POWER PLUG EXAMPLE
        #################################################
        - type: 'power_plug'
          name: 'Power plug'
          switch_entity: 'switch.xxxxxxx'
          graph_entity: 'sensor.xxxxxxx'

#################################################
#
#         NOT-FOUND - 404
#         !DON'T TOUCH!
#
#################################################
not-found:
  title: '404 not found'
  icon: 'mdi:motion'
  url: 'not-found'
  show_in_navbar: false
  show_header: true
  widgets:
    - type: 'text'
      content: |
        ## 404
        Sorry, the page you requested could not be found
