####################################################################
#         HTTP
####################################################################
# https://www.home-assistant.io/integrations/http/
#
# use_x_forwarded_for: true
# trusted_proxies: !secret http_trusted_proxies
#   cors_allowed_origins:
#     - http://localhost
#     - http://127.0.0.1
