####################################################################
#         TEXT TO SPEECH
####################################################################
# https://www.home-assistant.io/integrations/tts/
- platform: google_translate
  language: 'nl'
  cache: true
  cache_dir: '/tmp/tts'
  time_memory: 300
