- platform: template
  sensors:
    ####################################################################
    #
    #         MOTION SENSORS
    #
    ####################################################################
