- platform: template
  sensors:
    ####################################################################
    #
    #         ENTITY COUNTERS - USED FOR THE BADGE INDICATORS
    #
    ####################################################################

    ####################################################################
    #         LIGHTS
    ####################################################################
    current_lights_on:
      friendly_name: All Lights Currently On
      value_template: >-
        {{ expand('group.all_light_entities')|selectattr('state','eq','on')|list|count }}

    ####################################################################
    #         DEVICES
    ####################################################################
    current_devices_on:
      friendly_name: All Devices Currently On
      value_template: >-
        {{ expand('group.all_device_switch_entities')|selectattr('state','eq','on')|list|count }}

    ####################################################################
    #         MOTION
    ####################################################################
    current_motion_sensors_on:
      friendly_name: All Motion Sensors Currently On
      value_template: >-
        {{ expand('group.all_motion_sensor_entities')|selectattr('state','eq','on')|list|count }}

    ####################################################################
    #         BINARY
    ####################################################################
    current_binary_sensors_on:
      friendly_name: All Binary Sensors Currently On
      value_template: >-
        {{ expand('group.all_binary_sensor_entities')|selectattr('state','eq','on')|list|count }}

    ####################################################################
    #         DOORS
    ####################################################################
    current_doors_open:
      friendly_name: All Doors Currently Open
      value_template: >-
        {{ expand('group.all_door_sensor_entities')|selectattr('state','eq','on')|list|count }}

    ####################################################################
    #         WINDOWS
    ####################################################################
    current_windows_open:
      friendly_name: All Windows Currently Open
      value_template: >-
        {{ expand('group.all_window_sensor_entities')|selectattr('state','eq','on')|list|count }}

    ####################################################################
    #         CLIMATE ENTITIES
    #         !IMPORTANT
    #         check value_template in how the totals are summed up,
    #         there might be hvac_modes that aren't defined yet! This
    #         may cause the sum of the climate totals to be incorrect
    ####################################################################
    current_climate_entities_on:
      friendly_name: All Climate Entities Currently On
      value_template: >-
        {% set heat = expand('group.all_climate_entities')|selectattr('state','eq','heat')|list|count %}
        {% set cool = expand('group.all_climate_entities')|selectattr('state','eq','cool')|list|count %}
        {% set fan = expand('group.all_climate_entities')|selectattr('state','eq','fan_only')|list|count %}
        {% set heat_cool = expand('group.all_climate_entities')|selectattr('state','eq','heat_cool')|list|count %}
        {% set dry = expand('group.all_climate_entities')|selectattr('state','eq','dry')|list|count %}
        {% set total = heat + cool + fan + heat_cool + dry %}
        {{ total }}

    ####################################################################
    #         COVERS
    ####################################################################
    current_covers_open:
      friendly_name: All Covers Currently Open
      value_template: >-
        {{ expand('group.all_cover_entities')|selectattr('state','eq','open')|list|count }}

    ####################################################################
    #         GARAGE DOORS
    ####################################################################
    current_garage_doors_open:
      friendly_name: All Garage Doors Currently Open
      value_template: >-
        {{ expand('group.all_garage_door_entities')|selectattr('state','eq','open')|list|count }}

    ####################################################################
    #         FANS
    ####################################################################
    current_fans_on:
      friendly_name: All Fans Currently On
      value_template: >-
        {{ expand('group.all_fan_entities')|selectattr('state','eq','on')|list|count }}

    ####################################################################
    #         DETECTORS
    ####################################################################
    current_detectors_on:
      friendly_name: All Detectors Currently On
      value_template: >-
        {{ expand('group.all_detector_entities')|selectattr('state','eq','on')|list|count }}

    ####################################################################
    #         SECURITY
    ####################################################################
    current_security_entities_on:
      friendly_name: All Security Entities Currently On
      value_template: >-
        {{
          states('sensor.current_doors_open') | int +
          states('sensor.current_windows_open') | int +
          states('sensor.current_motion_sensors_on') | int
        }}
