- platform: template
  sensors:
    ###################################################################
    #        FRONTEND GREETING TODO: fix below with input_texts
    ####################################################################
    greeting:
      friendly_name: Greeting
      value_template: >-
        {% set hour = now().hour %}
        {% set minute = now().minute %}
        {% if hour <= 5 %} 
          Good Night <span>{{'\U0001F634'}}</span>
        {% elif hour <= 11 and minute <= 59 %}
          Good Morning <span>{{'\u2615\uFE0F'}}</span>
        {% elif hour <= 17 and minute <= 59 %}
          Good Afternoon <span>{{'\U0001F44B\U0001F3FB'}}</span>
        {% elif hour <= 23 and minute <= 59 %}
          Good Evening <span>{{'\U0001F44B\U0001F3FB'}}</span>
        {% else %}
          Good day <span>&#x1f44b;</span>
        {% endif %}
