#################################################
#
#         CUSTOM CONFIG
#
#################################################
home:
  title: 'Home'
  icon: 'mdi:home-assistant'
  url: 'home'
  show_in_navbar: true
  show_header: true
  rows:
    - widgets:
        - type: markdown
          content: 'Add some widgets to your custom.config.yaml'

#################################################
#
#         NOT-FOUND - 404
#         !DON'T TOUCH!
#
#################################################
not-found:
  title: '404 not found'
  icon: 'mdi:motion'
  url: 'not-found'
  show_in_navbar: false
  show_header: true
  widgets:
    - type: 'text'
      content: |
        ## 404
        Sorry, the page you requested could not be found
