#################################################
#
#         DUMMY AUTOMATION
#
#################################################
# https://www.home-assistant.io/docs/automation/yaml/
#
# - alias: 'Dummy Automation'
#   trigger:
#     - platform: template
#       value_template: |
#         {% if ((states('sensor.temperature') is defined) %}
#           True
#         {% endif %}
#
#   action:
#     - service: notify.notify
#       data:
#         message: Dummy message
#         title: Dummy Title
