# https://www.home-assistant.io/lovelace/
mode: yaml

# Add the HACS resources manually, since I noticed adding a
# a add-on through HACS doesn't always add this by propely
resources: !include lovelace-resources.config.yaml
dashboards:
  hass-nolu:
    mode: yaml
    title: Nolu
    icon: mdi:home-assistant
    show_in_sidebar: true
    filename: nolu/nolu.yaml
